### PR TITLE
Clay with comments!

### PR DESCRIPTION
**Pull request by philipcmonk**

### CODE REVIEW

**Comment by joemfb** [comment]
What is this? This is not the urbit I signed up for!

looks awesome, btw

**Comment by philipcmonk** [comment]
I'd encourage people to read this and ask questions.  I don't have time to be the sole owner of clay, so it'd be awesome if the community can take ownership of this!

**Comment by juped** [comment]
This isn't in - you wouldn't expect the thing that just adds comments to cause any problems, but it contains a partial refactoring that does not compile

**Comment by cgyarvin** [comment]
Not super worried about this -- I've pulled it into cc-release.

**Comment by ohAitch** [comment]
Uh, does it compile in cc-release?

**Comment by cgyarvin** [comment]
Strangely, it does!

**Pull request merged**
