### PR TITLE
Comments, talk feed, &c

### PR DESCRIPTION
**Pull request by galenwp**
General frontend improvements.  This has changes in `%e` and `%f`, but @ohAitch can advise as to how safe this is to deploy.

### CODE REVIEW

**Comment by galenwp** [comment]
Oh, this can probably go out.  Right @ohAitch ?

**Comment by juped** [comment]
I don't see why not.

**Comment by juped** [comment]
Actually, I guess those are real type changes, not renames. I'll wait for him

**Comment by ohAitch** [comment]
All the state adapters are there, and this has been run on every urbit.org ship recently, so it should be fine.

**Comment by juped** [comment]
I'll believe you over Github!

**Pull request merged**
