### PR TITLE
improve performance for writing files, rebuilding tree

### PR DESCRIPTION
**Pull request by ohAitch**
- consolidated clay subscriptions by path
- fewer repeated %cy requests for missing files

### CODE REVIEW

**Comment by juped** [comment]
There's some problem with this where it hangs on initial startup.

**Comment by ohAitch** [comment]
That is… certainly a problem

**Comment by ohAitch** [comment]
Hm, is it possible to kick a pr commit list? Everything until 1fd7120 just got merged by #137. (Also, my double-solid https://www.dropbox.com/s/4pydrsi47h8az95/c9c5c69.pill boots fine, what does the hang look like?)

**Comment by juped** [comment]
1. Just ignore Github, it's trash
2. Hangs on <<newt>> forever, probably initial clay sync

**Comment by ohAitch** [comment]
Okay yes, getting stuck on `«newt»` after I actually copied out the pill properly.

**Pull request merged**
