### PR TITLE
use compiler cache in ++ap-slam check

### PR DESCRIPTION
**Pull request by ohAitch**

### CODE REVIEW

**Comment by juped** [comment]
Unfortunately, this still introduces slowness - we're going to have to hold off on this stuff until next week

**Comment by juped** [comment]
When you get a chance, can you confirm that this isn't slow so it can go back in?

**Comment by ohAitch** [comment]
Will do, the slowness would be at least as noticeable as the event log one
was right?

**Comment by juped** [comment]
It's supposed to be super slow, yeah

**Comment by ohAitch** [comment]
Rebased on top of master and tweaked to not be performing an uncached `slot`.

**Pull request merged**
