### PR TITLE
3-fixed (unary sample) %cnsg

### PR DESCRIPTION
**Pull request by joemfb**
forward-ports and stages #381

/cc @ohAitch

### CODE REVIEW

**Comment by ohAitch** [comment]
you'll want to push the intermediate commits so the pilling chain actually goes through, and after the first one bump `.travis/pin-parent-pill-pier.url` two times to refer to the commits they respectively compile under
do you have permissions to push tags to **urbit/arvo**? I can probably take this over if not

**Comment by joemfb** [comment]
If you could, that would be great! I don't think I have any access to directly manipulate this repository.

**Comment by ohAitch** [comment]
(alternately, the staging can be avoided entirely if you just push a `hoon.hoon` with `=- ~(gas by -)` instead of the two uses of tall form `%~`, which I maybe could have thought of before  you wrote these sorry)

**Comment by joemfb** [comment]
It's no problem, these weren't exactly difficult changes. Feel free to cherry-pick whatever's useful here.

**Comment by ohAitch** [comment]
Thanks, I grabbed ++expn into db7120d which [at this rate](https://travis-ci.org/urbit/arvo/builds/362296092) looks like it'll succeed :3

**Comment by ohAitch** [comment]
huh it occurs to me that this *is* totally necessary for deployment to live network, hmm

**Comment by ohAitch** [comment]
@keatondunsford this is now deployable I think, though make sure to go through all the commits individually. (in theory, you could do just the three checkmark ones, but I remember there being issues where a reboot and app-reload in the same commit would be sequenced incorrectly)

**Comment by keatondunsford** [comment]
@ohAitch Cool. I'll get to this and the other PRs soon when I finish up a couple of other things. Thanks for checking on this.

**Comment by hoclun-rigsep** [comment]
Ah, very cool. I regret not having seen this through myself.

**Comment by keatondunsford** [comment]
@hoclun-rigsep Thanks for catching the original issue! ~zod's work continues.

**Comment by hoclun-rigsep** [comment]
On April 11, 2018 7:02:38 PM EDT, Keaton Dunsford <notifications@github.com> wrote:
>@hoclun-rigsep Thanks for catching the original issue! ~zod's work
>continues.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/urbit/arvo/pull/698#issuecomment-380622464

You haven't heard the last of me...
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
