### PR TITLE
urbit/tree@4d2e9c9

### PR DESCRIPTION
**Pull request by galenwp**
Might have mangled the history here.  Sorry.

### CODE REVIEW

**Comment by juped** [comment]
Could you replace this with two new PRs updating tree, one based on `master` and one based on `maint-20160818`?

**Comment by galenwp** [comment]
My default approach will be to just create PRs with fresh `.js`.  Sound good?

**Comment by juped** [comment]
I think so? What does that mean, exactly?

**Comment by galenwp** [comment]
Ah, don't worry about it.  Pretty sure that's right.

**Pull request closed without merging**
