### PR TITLE
simple channel filtering

### PR DESCRIPTION
**Pull request by galenwp**
This makes it possible to filter talk on a specific channel.  It's really simple, but it does work.

### CODE REVIEW

**Comment by galenwp** [comment]
I did test this on a comet.  If anyone is impatient for the feature, feel free to throw the `web/talk/main.js` onto your ship.  Could be a good idea to `|merge %sandbox ~your-urbit %home` first and `|serve %sandbox`.

**Comment by ohAitch** [comment]
Don't we already do something similar if you put a room in the query string?

**Comment by galenwp** [comment]
Do you remember the parameter name?  This basically just makes the UI understandable.

**Comment by joemfb** [comment]
I scanned this diff briefly -- it looks like it removes special-case handling of fora posts. Apologies if I'm must confused ... ;)

**Comment by galenwp** [comment]
Good catch. Let me take another look.

**Comment by galenwp** [comment]
You're right, and I don't want to remove that.  But I also can't find that code in the `/talk` repo.  @ohAitch ?

**Comment by galenwp** [comment]
Got it.  I think this is ready now.

**Pull request merged**
