### PR TITLE
adds support for optional models to %tstr aliases

### LINKED ISSUE #585: =* tistar should allow for optional type annotation
`=*` is a rune strictly used for code readability, and being able to add in a type annotation seems to be in line with that.

Should help with sanity checks for both the writer ("I expect this thing here to be of this type") and the reader ("what type is the data that `p.q.r.s.dat` refers to again?").

### PR DESCRIPTION
**Pull request by joemfb**
closes #585 

As this PR includes an incompatible change to `+hoon`, it has to be carefully staged. Since the changes affect the compiler, that staging must be coordinated with the jets in vere. I'll link those paired changes back to here, since the relevant PR doesn't yet exist.

Here's the procedure:

- boot a fake-zod from arvo master, vere with %tstc additions
- sync in / reset to first two arvo commits, (adds %tstc, replace all %tstr uses)
- disable |autoload
- sync in next arvo commit (updates %tstr to match %tstc)
- +solid, boot a new fake-zod (vere with +buss updates)
- sync in next arvo commit (replace all %tstc uses with %tstr)
- disable |autoload
- sync in next arvo commit (removes %tstc)
- +solid, boot a new fake-zod (vere with %tstc removal)

Or, simply boot a new fake-zod with the latest relevant vere changes and 
[tstr-toro.pill.tar.gz](https://github.com/urbit/arvo/files/1854520/tstr-toro.pill.tar.gz).

As for the changes themselves, they're mostly unremarkable. On thing worth calling out is that `+buss` (called by `+mint`, `+mull`, and `+play`) now calls back into `+open:ap`, which is a little odd. It'd probably be preferable to compute the bunt up-front, but I'm not sure how to that without having separate hoons to represent aliases pre and post macro expansion. Any recommendations?

And finally, two more questions:

- I noticed that `+conk` is declared in `tree.c`, but has not %fast hint. Is that deliberate?
- What exactly is the `%1` branch of `+toga` for? I can't seem to find any functionality that makes use of it.

### CODE REVIEW

**Comment by ohAitch** [comment]
Since it has a mandatory paired `urbit/urbit` change, this is not in a **master** PR in any immediate sense, right? Do we still have a **next-breach** branch?

**Comment by keatondunsford** [comment]
@joemfb @ohAitch What is the status of this?

**Comment by cgyarvin** [comment]
This should be merged not into master but into my research-fjord paired
branch, where a bunch of stuff doesn't respect continuity at all.

**Comment by keatondunsford** [comment]
Alright, I'm going to leave this one hanging then.

**Comment by ohAitch** [comment]
Should we create a **cc-release** branch, close this PR, and reopen the non-adapter section of it against said branch?

**Comment by keatondunsford** [comment]
Since we're breaching, is this worth refactoring to get in?

**Comment by joemfb** [comment]
This has separate been staged for research-fjord: https://github.com/cgyarvin/arvo/pull/2. @cgyarvin, is there any reason to breach this in now, or should it just come in with the overall language changes?

**Comment by joemfb** [comment]
closing as obsolete

**Pull request closed without merging**
