### PR TITLE
should have been cleaned by factor

### PR DESCRIPTION
**Pull request by galenwp**
As discussed: pretty sure these can be taken out for now.  Right @cgyarvin?

### CODE REVIEW

**Comment by ohAitch** [comment]
Is lunt the "local subs exercise terminal-permissions on their
co-hosted ships" vane? All of these should come out of the tree, though I'd
want to double check that there exist branches for their development.

**Comment by cgyarvin** [comment]
Yes.

On Mon, Mar 14, 2016 at 1:05 PM, Galen Wolfe-Pauly <notifications@github.com

**Comment by galenwp** [comment]
They certainly exist in the history.

**Comment by galenwp** [comment]
Let the record show @ohAitch and @cgyarvin agree that this should be merged.

**Comment by galenwp** [comment]
Although @ohAitch and I agree that having the drafts of these vanes exist at a tag would be convenient.

**Pull request merged**
