### PR TITLE
disallows duplicate arms in ++wisp

### PR DESCRIPTION
**Pull request by joemfb**
added this now that #270 has been merged -- see #199 for discussion.

closes #199

### CODE REVIEW

**Comment by juped** [comment]
But does it work? (Serious question, the status of this has been murky to me.)

**Comment by joemfb** [comment]
Yes. As demonstrated in #199, it works in generators and `:dojo` expressions (although you have to manually for a "reload" of `:dojo` first). I just tested it in apps and vanes, it works there as well.

**Comment by joemfb** [comment]
The UX could definitely be improved: from more sophisticated error logging (currently `[%duplicate-arm %foo]`) to earlier detection when parsing (currently errors at the arm *after* the duplicate arm, or the end of the core, whichever comes first)

**Comment by juped** [comment]
Cool. Expect it Friday.

**Pull request merged**
