### PR TITLE
Refactor /lib/*auth* with better names and encapsulation

### PR DESCRIPTION
**Pull request by ohAitch**
Downstream of #108

### CODE REVIEW

**Comment by juped** [comment]
Well, OK

**Comment by ohAitch** [comment]
Elaborate? This is a refactoring of libraries for sec/, it depends on the new API drivers because those are in the sec/ model, and use said libraries. In the spirit of continuing to learn your standards for non-troll merge messages, what should `Get remaining security drivers for normalization` have been?
(Or is this not an ancestry graph shape issue?)

**Comment by juped** [comment]
No issues. Though now that you mention it, asana is just one of the remaining security drivers. You missed digitalocean and instagram.

**Comment by ohAitch** [comment]
I got DO in 6b13e6d, and I think Instagram was already merged. I think ault011/asana was just the recentmost @ault011 branch, with all previous changes in it.

**Comment by juped** [comment]
image

Admittedly, I don't know how DO-related dropboxapi.hoon is, but it's also missed

(I don't think you have to do anything about it, though.)

**Comment by ohAitch** [comment]
dropboxapi.hoon presumably already existed at the fork commit "touched
up…dbox and insta", and I'm guessing the later change merged cleanly. I
think it's one of the ones I explicitly tested before the pull
request(commented command on first line) because I already had the app key
set up, though Digital Ocean wasn't in that set.

**Comment by ohAitch** [comment]
@ault011 when you have a spare moment, can you rerun the DO test case on
this branch? I have an API .atom in my pier for everything else, and I
don't remember any of them failing.

**Pull request merged**
