### PR TITLE
Handle the move which makes the ova first

### PR DESCRIPTION
**Pull request by eglaysher**
Ref #962

### CODE REVIEW

**Comment by philipcmonk** [comment]
I feel like this should just reorder the moves in the various `?-` cases rather than removing the flop at the end.  Virtually every core that maintains a `(list move)` flops it at the end so that incrementally adding is easy and happens in the order you'd expect.

**Comment by ohAitch** [comment]
Yeah, if the issue is (the moves of) notify-clients ought to happen after
set-wake, it would be a lot clearer if the invocations were reordered
accordingly in ++call.

**Comment by ohAitch** [comment]
Hm, or barring that due to data flow constraints, a renaming to e.g.
(set-wake-before moves)

**Comment by belisarius222** [comment]
A comment explaining why we prepend the Unix move would also be helpful.

**Pull request merged**
