### PR TITLE
Fix presence, better this time

### PR DESCRIPTION
**Pull request by ohAitch**
Single-machine testing caught the loop previously experienced, and uncovers no issues with this version; multi-machine testing tbd. ~should~ be fine but I thought that last time P:

### CODE REVIEW

**Comment by juped** [comment]
What's "single-machine testing"? Fake federated stars?

**Comment by ohAitch** [comment]
And planets, yeah.

**Comment by cgyarvin** [comment]
Yes.

**Comment by juped** [comment]
This is in

**Comment by ohAitch** [comment]
I am somewhat alarmed that it will bring down the network again and we
won't know if that's actually its fault, but I suppose I really haven't
been making enough progress on the testing infrastructure to hold this off
forever

**Comment by juped** [comment]
It never brought down the network to begin with, just spammed people.

**Pull request closed without merging**
