### PR TITLE
Enable js urb.bind to a foreign {ship}

### PR DESCRIPTION
**Pull request by ohAitch**
by implementing the "subscription with a mark translation on all results" %peel code path in gall

@cgyarvin requesting sanity-check

### CODE REVIEW

**Comment by ohAitch** [comment]
Also this branch shouldn't be on the main repo whoops

**Comment by juped** [comment]
Can't edit it to be the right branch, have to close it and reopen a new one

**Comment by joemfb** [comment]
The edit button at the top right of PR (after the title) lets you change the target branch.

**Comment by ohAitch** [comment]
Unfortunately what I actually need to change is the source branch, which I accidentally created on the main repo. Dupe #378 opened

**Comment by joemfb** [comment]
*continues his incredible run of "helpfulness"*

**Pull request closed without merging**
