### PR TITLE
fix gh and ask apps

### PR DESCRIPTION
**Pull request by belisarius222**

### CODE REVIEW

**Comment by mattlevan** [comment]
@belisarius222 have you checked to see if these fixes allow for exploration of one's GitHub repo issues as is exemplified in arvo docs' API.md? Initial testing on my end suggests more fixing is needed, but I'll be testing more thoroughly tomorrow morning.

**Comment by belisarius222** [comment]
@mattlevan I did not check that, so I wouldn't be too surprised if there's a bug. This PR is dead, though. Its commits have already been merged into master.

**Comment by mattlevan** [comment]
@belisarius222 Ah ok, I assume those fixes were included in the `sec-fixes` branch merged in urbit/arvo#443?

**Comment by belisarius222** [comment]
Yes, that's correct.

**Pull request closed without merging**
