### PR TITLE
Language/dojo improvements for teaching.

### PR DESCRIPTION
**Pull request by cgyarvin**

### CODE REVIEW

**Comment by juped** [comment]
Spurious commit b39b238 is a recalcitrant offender. The actual patch here is based on the tree as of d690fa4. Please run `git rebase d690fa4` on branch `teaching`.

**Comment by juped** [comment]
Extra points if `--whitespace=fix` is involved, but I've never really been that bothered by trailing spaces.

**Comment by cgyarvin** [comment]
Hm, I thought I *wasn't* supposed to merge from master before posting
changes?

**Comment by juped** [comment]
You aren't! But the last time you did it is still hanging out there, trying to sneak in to the repository...

**Comment by cgyarvin** [comment]
"Fatal: need a single revision"
"invalid upstream d690fa4"

**Comment by juped** [comment]
You should *fetch* origin. Git doesn't autosync, alas.

**Comment by cgyarvin** [comment]
Ok, I believe this is properly pushed.

**Comment by juped** [comment]
:(

I'll figure it out somehow

**Comment by juped** [comment]
- [x] rebase as mentioned above - correct
- [x] made some more commits - correct
- [x] tried to push - ok

I am pretty sure you got an error here that suggested you might want to type `git pull` to resolve it

- [ ] believed git and typed `git pull` - bad

You believed the git message, you must never believe the git messages!

Thanks for trying though.

**Comment by cgyarvin** [comment]
Hm.  I might have done that...

**Comment by juped** [comment]
Closed for cleanup

**Pull request closed without merging**
