### PR TITLE
sec/ fixes

### PR DESCRIPTION
**Pull request by belisarius222**
Went through the breach checklist and got the security drivers working, with the exception of twitter, which is broken in a non-obvious way that will require further debug work.

Most of this was zuse namespace changes, with a couple syntax errors from new hoon, and one case of requiring a new `^-` in a `|-`.

### CODE REVIEW

**Comment by joemfb** [comment]
@belisarius222, did you see #415?

**Comment by belisarius222** [comment]
I had not seen that! Strangely, I didn't experience any of the errors described in that PR. I got a response from twitter with an error 32: "could not authenticate you."

I expect we'll fix `:twit` after the continuity breach, at which point we'll integrate your PR. It looks like it'll merge pretty smoothly.

**Comment by belisarius222** [comment]
@cgyarvin This is up to date with master now.

**Comment by belisarius222** [comment]
Hold off on merging this; I think there are new syntax errors.

**Comment by belisarius222** [comment]
Ok, should be good to go now.

**Comment by belisarius222** [comment]
This PR is now out-of-date with master. Tried to use github's web-based conflict resolver, which ended poorly, so I'm doing some git surgery now to clean this up.

**Comment by belisarius222** [comment]
Up-to-date again, after a rebase that was only mildly karmically damaging (of course, even minor tampering with git history opens a rift in spacetime). @cgyarvin it would be nice to get this merged before it gets out of date again.

**Comment by cgyarvin** [comment]
Sorry!  On it now.

**Pull request merged**
