### PR TITLE
Enable js urb.bind to a foreign {ship}

### PR DESCRIPTION
**Pull request by ohAitch**
by implementing the "subscription with a mark translation on all results" %peel code path in gall

(dupe of #373)

### CODE REVIEW

**Comment by ohAitch** [comment]
Does the main `%l` part have problems long-term, which I should open an
issue for?

**Comment by cgyarvin** [comment]
%|?  What mean?

**Comment by juped** [comment]
`%l` (Anton tried to monospace it, but web 3.0 tech failed him), not `%|`

**Comment by ohAitch** [comment]
Right, pointers
The majority of this patch is a [new type of rook](https://github.com/urbit/arvo/pull/378/files#diff-3d799378415e1e20fa632da2978b72b3R16), i.e. gall "forward ames message", which handles "translate me later" %peel subscriptions.

**Comment by ohAitch** [comment]
No actually my mistake there was trying to put md formatting in an email reply instead of using the actual Web 3.0 tech :P

**Comment by ohAitch** [comment]
Anyone on a righteous Web 0.5 mail client shouldn't see any non-monospaced text anyway…

**Comment by ohAitch** [comment]
(Also in answer to my own question, it might be causing the defer-mack collisions, I was right that the %doff handling should be in gall somehow, giving it a chance to unregister the crash handler duct)

**Pull request closed without merging**
