### PR TITLE
Short ship names in prompt

### PR DESCRIPTION
**Pull request by Fang-**
As requested in #152, replaces the full ship name in the prompt with a shortened version like those used in talk. (ie `~todsel_lithex` for comets, `~torbyt^sogwyx` for moons)

To facilitate this, I added a `++shortship` arm to `lib/sole.hoon` that produces the shortened name as a tape. I also updated `app/talk.hoon` to use that arm for name shortening.

### CODE REVIEW

**Comment by joemfb** [comment]
I think this messes with the `:talk` alignment for `$czar` and `$king`. (I feel kinda responsible, since I recommended this approach ... ;))

**Comment by juped** [comment]
Something like that belongs in zuse next to ``++sein`` and friends with a cutesy four-letter name...

**Comment by Fang-** [comment]
@joemfb It would, if I hadn't done the following in `app/talk.hoon`:
```
=+  raw=(shortship %p p.one)
(runt [(sub 14 (lent raw)) ' '] raw)
```
If the short ship name is less than 14 characters, it gets left-padded to fill up that space. I tested it (by getting the modified talk to load in a bunch of scrollback which included messages by a galaxy), and alignment was unaffected.

**Comment by Fang-** [comment]
@juped I'm taking suggestions. Best I can come up with is `++snam` or `++naem`.

**Comment by joemfb** [comment]
Nice! (... and sorry for the reading-comprehension-fail on my part ...)

**Comment by chc4** [comment]
Four-letter stdlib names are only fun if they are valid [Scrabble words](https://github.com/urbit/urbit/blob/master/Spec/flw.txt) :-)

`++cite` might be a good one? Or you can follow the pattern of `++glam` and `++gnom` and `++gnow` - something like `++glim` or `++gnat`, something with a "small" connotation.

**Comment by Fang-** [comment]
`++cite` sounds nice! How's this look?

**Comment by Fang-** [comment]
So apparently stars can also make moons, and they look like `~somtin-somtin-sarnom`. Since they classify as `%earl`, like planet moons, the current code for `++cite` doesn't work correctly for those moons.

I see talk uses `~sarnom^` for star moon shortform. It seems to be a by-product of the current `++sn-curt` implementation. Do we want to keep it like that, or use `~^sarnom`, or something else entirely?  
Can galaxies also make moons? What do they look like?

Let me know so I can update `++cite` for non-planet moons (and hopefully get this pulled then).

**Comment by galenwp** [comment]
Stars making moons somehow sounds like a bug to me.

**Comment by cgyarvin** [comment]
It's not a bug, it's math!  :-)

**Comment by Fang-** [comment]
I rewrote `++cite` to work correctly with all ship types, both regular and short names. (Short names for moons and comets are explained nicely on [The ~nimbus Reference](http://nimbus.urbit.org/help/), special thanks!)

This moves the `^` for star moons to the front, ie `~^nimbus`. I personally think that makes a tad more sense, logically and visually. It's going to look a bit wonky anyway, and this seems cleaner than a trailing `^`.

Output examples for all cases:
```
> (cite ~zod)  ::  galaxy
"~zod"
> (cite ~nimbus)  ::  star
"~nimbus"
> (cite ~doznec-dozzod-nimbus)  ::  star moon
"~^nimbus"
> (cite ~figdul-mappyl)  ::  planet
"~figdul-mappyl"
> (cite ~fipfes-fipfes-figdul-mappyl)  ::  planet moon
"~figdul^mappyl"
> (cite ~fipfes-figdul-mappyl)  ::  short planet moon
"~figdul^mappyl"
> (cite ~doznec-dozzod-dozzod-dozzod--dozzod-dozzod-dozzod-dozzod)  ::  comet
"~doznec_dozzod"
> (cite ~doznec--dozzod-dozzod-dozzod-dozzod)  ::  short comet
"~doznec_dozzod"
```

**Comment by galenwp** [comment]
This looks nice.

**Comment by juped** [comment]
Changed on my end to use long moon names in the prompts (special case for $earl)

**Comment by juped** [comment]
This is in

**Pull request closed without merging**
