### PR TITLE
HOTFIX disable presence reporting

### PR DESCRIPTION
**Pull request by ohAitch**
(currently deployed on zod)

### CODE REVIEW

**Comment by ohAitch** [comment]
@juped @cgyarvin should I just merge this already?

\> currently deployed on zod

**Comment by juped** [comment]
It's deployed on zod, right?

**Comment by ohAitch** [comment]
It's deployed on zod

**Comment by juped** [comment]
I mean, the merged version

You can merge it, but you have to deploy the merged version if you do

**Comment by juped** [comment]
(I avoided doing that due to people hotfixing the live zod at the time, but I think that's over.)

**Comment by ohAitch** [comment]
It's based on what was deployed at the time, which looks like it's missing
3 commits yeah

**Comment by cgyarvin** [comment]
Every time what's on ~zod isn't what's on the purportedly matching github
branch, this is basically an emergency.  There are various reasons it can
happen but it should get cleaned up.

This specific work item came about because I was maintaining the network by
doing manual upgrades to the current maintenance branch on all the stars,
only to discover the little unmerged timebomb.

**Comment by ohAitch** [comment]
The merge seems to still be on `/=base=`, but gone from `/=home=` and `/=kids=`; @juped have there been any recent changes that could have clobbered this, or should I just remerge home and kids from base?

**Comment by juped** [comment]
Redirect to @cgyarvin since he was the last one to do something to zod, and I think he did something different to stop the crashing

**Comment by cgyarvin** [comment]
I'm working with Anton on this.

**Comment by juped** [comment]
When you're done, tell us what you did.

**Comment by ohAitch** [comment]
Am done: brought down zod, ran rsync to zod/home and zod/kids, brought zod
back up again. This bounced the network some over the following hour, but
seems to have stabilized with no presence notifications or crashes in
sight. There was a single [%c %went] printf that Curtis said might indicate
a bad merge, but I couldn't find any errors on the stars; maybe some sub
has a sync running to zod?

**Pull request merged**
