### PR TITLE
Enabled doccords in hall.

### PR DESCRIPTION
**Pull request by eglaysher**
This goes through the new hall files and makes the doccords syntax compile.

@Fang-

### CODE REVIEW

**Comment by Fang-** [comment]
This is great, thanks so much for going over all my temporary-style comments!

I'm kind of sad to see the column-57 comments go, but it also reads more like an actual document this way.

**Comment by ohAitch** [comment]
Imo they're incredibly helpful as context cues for where all the ++'s are,
but I've noticed that in general my spacing intuitions don't fit super well
with ++deco styling

**Comment by eglaysher** [comment]
I don't particularly mind the column-57 comments on the gates. However, this doesn't compile:

```
++  gate         :<  short comment
  :>  long comment
  42
```

**Comment by ohAitch** [comment]
Wh?

*looks at the parsers*

**Pull request merged**
