### PR TITLE
Eyre security drivers

### PR DESCRIPTION
**Pull request by ohAitch**
Breaching. Has numerous issues, most of which aren't.

### CODE REVIEW

**Comment by juped** [comment]
>Merge branch 'master' into
pls

**Comment by ohAitch** [comment]
I distinctly remember you said it's fine as long as the commit message
contains a sufficiently good reason, and that "conflicts: foo" is a
sufficiently good reason ^-^

**Comment by ohAitch** [comment]
Commit description*

**Comment by juped** [comment]
It can be an *explanation*, but it's not a reason, especially at the end of a branch's life...

I will forward you the relevant Linus email / Junio blog post package, or you can ask Curtis for it

**Comment by ohAitch** [comment]
Ah okay, yes plz if it contains the right way to do conflict resolution.

**Comment by juped** [comment]
In the meantime, you can make amends by: resetting this branch to 2db4f33, and telling me the solution to this conflict:

```
<<<<<<< .merge_file_9ss5Bi
    =+  bek=?+(r.top -.top {$ud $0} -.top(r da+now))
    (pass-note tea (ford-req bek [%cast mar $+cay]))
||||||| .merge_file_rL6r8h
    (pass-note tea (ford-req -.top [%cast mar $+cay]))
=======
    (execute tea -.top [%cast mar $+cay])
  ::
  ++  cast-thou
    |=  {mar/mark cay/cage}
    ?:  ?=($httr mar)  (give-sigh %& cay)
    (back si+~ mar cay)
>>>>>>> .merge_file_VDRkxi
```

which I assume is

```
    =+  bek=?+(r.top -.top {$ud $0} -.top(r da+now))
    (execute tea bek [%cast mar $+cay])
  ::
  ++  cast-thou
    |=  {mar/mark cay/cage}
    ?:  ?=($httr mar)  (give-sigh %& cay)
    (back si+~ mar cay)
```

**Comment by ohAitch** [comment]
Sure.

The resolution is correct; please define "tell you" in a publicly-visible
general sense though. Do I link to a conflicts-resolved version in the pull
request or sth?

**Comment by juped** [comment]
All I wanted to know was if that resolution was still correct with all the other branches merged in too.

In general you'd `git checkout -b eyre-sec-to-master master`, `git merge --no-ff eyre-sec`, and push both that and your regular merge-free `eyre-sec` somewhere.

**Comment by juped** [comment]
In most cases, that `stuff-to-master` merge would just go onto master unmodified; in the cases where it can't or doesn't, it still provides resolutions that can be automatically reused if the same conflicts occur.

**Pull request merged**
