### PR TITLE
Remove trailing whitespace & put check in CI

### PR DESCRIPTION
**Pull request by Fang-**
If we don't do it now we'll do it never.

May want to merge this into a different branch than master, depending on whatever decision comes out of discussion in #1018.

### CODE REVIEW

**Comment by joemfb** [comment]
I'm embarrassed to see some of my code in here.

**Comment by Fang-** [comment]
The best version of this PR makes CI fail when you're trying to check in trailing whitespace, but idk if that's desirable.

**Comment by joemfb** [comment]
I'd approve that.

**Comment by Fang-** [comment]
[That seems to work!](https://travis-ci.org/urbit/arvo/builds/481232890#L1043)

Would moving the test to earlier in CI (ie `before_install`) comply with common expectations of the Travis semantics?

**Comment by joemfb** [comment]
I think that would be fine -- this check seems best placed as early as possible.

**Comment by Fang-** [comment]
Alright, it's now the very first thing that's checked.

**Pull request merged**
