### PR TITLE
Fixed cross-ship URL hang

### PR DESCRIPTION
**Pull request by ohAitch**
Partial unblock state wasn't being persisted by `%ford`

### CODE REVIEW

**Comment by keatondunsford** [comment]
Just tried to load `http://localhost:8080/~nec/kids/=/web/` from a ~zod. Hung for a while, then printed:

```
...
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/elem/ren]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/txt/mar]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hoon/txt/mar]
>> [%camping %c %x [p=~nec q=%kids r=[%ud p=2]] s=/hoon/txt/mar]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/index/tree/ren]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hoon/index/tree/ren]
>> [%camping %c %x [p=~nec q=%kids r=[%ud p=2]] s=/hoon/index/tree/ren]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/mar]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/index/tree/mar]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hoon/index/tree/mar]
>> [%camping %c %x [p=~nec q=%kids r=[%ud p=2]] s=/hoon/index/tree/mar]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/map-to-json/lib]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hoon/map-to-json/lib]
>> [%camping %c %x [p=~nec q=%kids r=[%ud p=2]] s=/hoon/map-to-json/lib]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/json/mar]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hoon/json/mar]
>> [%camping %c %x [p=~nec q=%kids r=[%ud p=2]] s=/hoon/json/mar]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/elem/tree/mar]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hoon/elem/tree/mar]
>> [%camping %c %x [p=~nec q=%kids r=[%ud p=2]] s=/hoon/elem/tree/mar]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/html/mar]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hoon/html/mar]
>> [%camping %c %x [p=~nec q=%kids r=[%ud p=2]] s=/hoon/html/mar]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hymn/mar]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hoon/hymn/mar]
>> [%camping %c %x [p=~nec q=%kids r=[%ud p=2]] s=/hoon/hymn/mar]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/snip/mar]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hoon/snip/mar]
>> [%camping %c %x [p=~nec q=%kids r=[%ud p=2]] s=/hoon/snip/mar]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/front/ren]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/jam/mar]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hoon/jam/mar]
>> [%camping %c %x [p=~nec q=%kids r=[%ud p=2]] s=/hoon/jam/mar]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/part/womb/mar]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hoon/part/womb/mar]
>> [%camping %c %x [p=~nec q=%kids r=[%ud p=2]] s=/hoon/part/womb/mar]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/womb/hood/lib]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hoon/womb/hood/lib]
>> [%camping %c %x [p=~nec q=%kids r=[%ud p=2]] s=/hoon/womb/hood/lib]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hall/lib]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hoon/hall/lib]
>> [%camping %c %x [p=~nec q=%kids r=[%ud p=2]] s=/hoon/hall/lib]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hall/sur]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hoon/hall/sur]
>> [%camping %c %x [p=~nec q=%kids r=[%ud p=2]] s=/hoon/hall/sur]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/old-phon/lib]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hoon/old-phon/lib]
>> [%camping %c %x [p=~nec q=%kids r=[%ud p=2]] s=/hoon/old-phon/lib]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/comments/tree/ren]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hoon/comments/tree/ren]
>> [%camping %c %x [p=~nec q=%kids r=[%ud p=2]] s=/hoon/comments/tree/ren]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/comments/web]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/comments/tree/mar]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hoon/comments/tree/mar]
>> [%camping %c %x [p=~nec q=%kids r=[%ud p=2]] s=/hoon/comments/tree/mar]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/time-to-id/lib]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hoon/time-to-id/lib]
>> [%camping %c %x [p=~nec q=%kids r=[%ud p=2]] s=/hoon/time-to-id/lib]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/404/web]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hoon/womb/web]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hoon/404/web]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/all/unmark/web]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/test/unmark/web]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hoon/talk/web]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hoon/dojo/web]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/main/womb/web]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/main/talk/web]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/css/lib/web]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/umd/testing/web]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/js/lib/web]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hoon/listen/web]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/umd/static/web]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/css/pack/web]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/js/pack/web]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/main/tree/web]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hoon/mar]
>> [%camping %c %x [p=~nec q=%kids r=[%ud p=2]] s=/umd/testing/web]
>> [%camping %c %x [p=~nec q=%kids r=[%ud p=2]] s=/umd/static/web]
>> [%camping %c %y [p=~nec q=%kids r=[%ud p=2]] s=/hoon/hoon/mar]
>> [%camping %c %x [p=~nec q=%kids r=[%ud p=2]] s=/hoon/testing/web]
>> [%camping %c %x [p=~nec q=%kids r=[%ud p=2]] s=/hoon/static/web]
[%ford-lost %c 73]
```

What's the last bit about?

**Comment by vvisigoth** [comment]
I've tried this with two ships on testnet with this commit and I still can't get anything to work. I'm still running into various versions of the same problem. 

@ohAitch how did you test this? Maybe I'm missing something.

**Comment by vvisigoth** [comment]
OK, I've now been able to get to keaton's error. On reload, this appears to throw you into https://github.com/urbit/arvo/issues/681

screen shot 2018-04-21 at 11 38 57 am

**Comment by vvisigoth** [comment]
Keaton, what's the best pre-681 commit?

**Comment by Fang-** [comment]
> Looks like it is trying to build the _previous_ page I tried to access.

For the record, I'm seeing this too. Seems you can work around it by closing the tab, opening a new one, and doing the request there. So it might be (partially) an eyre thing?

**Comment by Fang-** [comment]
Actually, maybe I lied? Unable to reproduce anymore at least. Might've been an oddity or incorrect observation on my end.

**Comment by keatondunsford** [comment]
@joemfb This didn't fix the intended issue completely, but @ohAitch seems to think the original logic here was incorrect. Should I merge this?

**Comment by joemfb** [comment]
It certainly looks like a logic bug that should be fixed, but my opinion isn't worth much here -- I'm not familiar with the background.

Since this doesn't change any interfaces, I don't see any reason to prioritize including these changes in a breach. I would wait and release them live when appropriate.

**Comment by joemfb** [comment]
Closing as won't merge -- ford has been entirely replaced.

**Comment by ohAitch** [comment]
And presumably has been tested at this use case, if it still exists? ^-^

**Pull request closed without merging**
