### PR TITLE
adds tape/list search gates

### PR DESCRIPTION
**Pull request by joemfb**
currently `++find` / `++fand` - another potential pair is `++indx` / `++inda`...

### CODE REVIEW

**Comment by joemfb** [comment]
some examples/testing:

```
> (find [3]~ (ly ~[1 4 2 5 3 8 3 0]))
[~ 4]
> (fand [3]~ (ly ~[1 4 2 5 3 8 3 0]))
~[4 6]
> (find ['a']~ "cbcabba")
[~ 3]
> (fand ['a']~ "cbcabba")
~[3 6]
> (find "ab" "cbcabba")
[~ 3]
> (find "" "")
~
> (find "a" "")
~
> (find "" "a")
~
> =+  b="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ipsum, ipsum ipsum."
  (fand "ipsum" b)
~[6 64 70]
> =+  a==+([a="a" b=18] |-(?~(b (weld a "b") $(a (weld a a), b (dec b)))))
  (find "aaaaaaab" a)
[~ 262.137]
> =+  a==+([a="a" b=20] |-(?~(b (weld a "b") $(a (weld a a), b (dec b)))))
  (find "aaaaaaab" a)
[~ 1.048.569]
```

(long examples cribbed from https://github.com/urbit/examples/blob/master/libs/strings-kmp/lib/strings-kmp.hoon)

Note: when run with `b=21`, that last example consistently triggers a stack-overflow, ending with:

``
    arvo
    ford
  <[1.222 23].[1.222 53]>
```

... which is `(mock ...)` in `++maim`.

**Comment by juped** [comment]
I don't think the line in ford where evaluation happens is that interesting to know. :)

**Comment by joemfb** [comment]
Figured the stack was relevant since it was dumped ... ;) I actually hadn't checked it for any other overflows.

Is "userland" nock always virtualized through? `++maim`?

**Comment by ohAitch** [comment]
*blames lack of !:*

**Comment by juped** [comment]
If it weren't virtualized, you'd see a bail.

**Pull request merged**
