### PR TITLE
various 151ification and other repair

### PR DESCRIPTION
**Pull request by ohAitch**
- partial port of generators
- ford cache issue
- fix tree, dojo marks

### CODE REVIEW

**Comment by ohAitch** [comment]
latest.pill updated?

**Comment by juped** [comment]
http HEAD is your friend (we have checksum headers!)

**Comment by ohAitch** [comment]
```http
➤ curl -I http://bootstrap.urbit.org/latest.pill
HTTP/1.1 200 OK
X-GUploader-UploadID: AEnB2UrU1zF1jJtudOIlfXPi7-fvAKq3TW4pcgHEH9EWpma-g1VPHB4EE2gWbEtZ07jAPRtXfjk9RYPOZj_9J2Poeu9hFA4_pA
Expires: Tue, 16 Feb 2016 23:21:20 GMT
Date: Tue, 16 Feb 2016 22:21:20 GMT
Cache-Control: public, max-age=3600
Last-Modified: Tue, 16 Feb 2016 21:29:09 GMT
ETag: "1aea7cb6f576fdc8253b22a8d9b05726"
x-goog-generation: 1455658149586000
x-goog-metageneration: 1
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 2300561
Content-Type: binary/octet-stream
x-goog-hash: crc32c=hO5gog==
x-goog-hash: md5=Gup8tvV2/cglOyKo2bBXJg==
x-goog-storage-class: STANDARD
Accept-Ranges: bytes
Content-Length: 2300561
Server: UploadServer
```
Are any of the opaque strings of numbers/hex/base64 a commit hash? Am I supposed to run `md5` on my latest.pill, and base64 that?

**Comment by juped** [comment]
There’s a couple hashes of the pill in there… compare to 84ae855ccecc492b20875fc030981e34ab722d2e.pill if you want

**Comment by ohAitch** [comment]
Both of which are expressed in base64. I suppose I could throw together a script that checks whether the pill you happen to have is the one on latest; I'd prefer for there to be some official registry of pillful commits though.

**Pull request merged**
