### PR TITLE
Remove 200ms delay in +run-builds in ford.

### PR DESCRIPTION
**Pull request by eglaysher**
In +run-builds in ford, the ordering of `~%  ...  |-`  expands to  `~%  ...  =<  $  |.`, which is wrong and causes a 200ms delay for reasons I suspect are related to battery registration. We then went through and made sure that the ~% is registered directly on the cores in a few places in Eyre, too.

Locally, it now takes about a second to roundtrip a message from landscape to urbit and back.

review: @ixv 
cc: @belisarius222

### CODE REVIEW

**Comment by cgyarvin** [comment]
Great — but that’s still insanely slow, brothers...

**Comment by cgyarvin** [comment]
Wow

**Comment by belisarius222** [comment]
Yikes! I apologize for my role in that ... uh ... misguided approach to jet-hinting. Hope I didn't do that anywhere else.

**Comment by joemfb** [comment]
@eglaysher, should this PR be against the release-candidate?

Based on that CI build log, I think some of parent axes in these hints are now wrong.

**Comment by cgyarvin** [comment]
Paul, a bad axis in a hint should definitely not be able to cause a
bail-foul... but if such a bug existed it wouldn't shock me :-/

**Comment by eglaysher** [comment]
Merely commenting out the `~%  ...  |-` block at the top of the top of /sys/vane/ford+run-builds causes a `bail: foul`. (Putting the ~% back fixes it.) 

Slipping this patch into a new zod makes the tests run the first time. Then it causes a `bail: foul` on each subsequent run of the test suite.

Building a new zod from the testnet-rc branch, running the ford tests, making a small change, and then running the ford tests again does not cause a bail.

**Comment by joemfb** [comment]
I'm not claiming that to be the cause -- just pointing the immense number of "parent not found" errors in the build log. It exceeds travis-ci's log length limit, so I can't even see the bail.

I believe the `%eyre` changes in this PR are unnecessary. There shouldn't be anything wrong with a jet registration hint that precedes pinning something to the subject and then producing a core. The only requirement is that the parent axis lines up.

**Comment by cgyarvin** [comment]
Obviously we're going to need to debug this with or without Paul's help :-/

**Comment by joemfb** [comment]
I've updated #879 to print a backtrace if we dump core in CI. Merging that, reparenting this on release-candidate, and fixing the parent axes would provide some nice context. Of course, that context is available in other ways ...

**Comment by belisarius222** [comment]
no one has summoned @frodwith?

**Comment by joemfb** [comment]
With urbit/urbit#1059 merged, is this PR ready to be revived?

**Comment by eglaysher** [comment]
Let me minimize the patch first.

**Comment by joemfb** [comment]
To fix CI, you'll probably need to bump `.travis/pin-vere-commit.txt` so it point to latest release-candidate.

**Comment by ixv** [comment]
You should merge this into release-candidate arvo too. testnet-rc is dead.

**Comment by joemfb** [comment]
Thanks @ixv, I just took the liberty of re-targeting this.

**Comment by eglaysher** [comment]
That doesn't work, the branches are too diverged. I'm going to just rebuild it.

**Comment by joemfb** [comment]
FWIW, you can always force-push to your side of a PR.

**Pull request closed without merging**
