### PR TITLE
HOON

### PR DESCRIPTION
**Pull request by belisarius222**
Urbit's stated mission is to modernize system software. This is an ambitious goal, however, and it's possible we've overreached. Sometimes it can be good to reevaluate some core design decisions to ensure we're on the right track.

One major, and somewhat contentious, decision made early on in the murky, pre-corporate days of the Urbit project was to use lower-case letters for all symbols in the hoon programming language. While this is obviously correct, both intuitively and mathematically, perhaps the world wasn't ready for it yet.

So, as a concession to popular languages such as COBOL and BASIC, I have taken the liberty of converting all of hoon to uppercase, forming the new language HOON.

You'll find it a little jarring at first to see so many large letters jutting boldly off the screen. But this is an important reminder that you're not working on Earth software anymore -- or, at least not Earth software from the past fifty years. Martians have no need to whisper. Alice has eaten one side of the mushroom, and now the real work begins.

After a little while, you'll come to see the beauty and inherent simplicity in this design. Of particular note are the mathematical and crypto algorithms, whose machinic grit and axiomatic purity can't be missed in HOON.

Some highlights:
https://github.com/belisarius222/arvo/blob/ceeb9c0e58c1cb49b3476b9c8ae9efe38bfbd27d/gen/metal.hoon
https://github.com/belisarius222/arvo/blob/ceeb9c0e58c1cb49b3476b9c8ae9efe38bfbd27d/sys/hoon.hoon#L3240
https://github.com/belisarius222/arvo/blob/ceeb9c0e58c1cb49b3476b9c8ae9efe38bfbd27d/sys/hoon.hoon#L1076
https://github.com/belisarius222/arvo/blob/ceeb9c0e58c1cb49b3476b9c8ae9efe38bfbd27d/sys/zuse.hoon#L7209
https://github.com/belisarius222/arvo/blob/ceeb9c0e58c1cb49b3476b9c8ae9efe38bfbd27d/sys/zuse.hoon#L7652
https://github.com/belisarius222/arvo/blob/ceeb9c0e58c1cb49b3476b9c8ae9efe38bfbd27d/sys/vane/ames.hoon#L468

PS The unit tests have yet to appreciate the momentousness of this new paradigm. As we all know, though, testing is just a crutch for people who can't write correct code anyway. We have no choice but to ignore the testing server's petty whining and proceed as planned.

### CODE REVIEW

**Comment by cgyarvin** [comment]
I knew it was only a matter of time before Ted stayed up all night and went
completely off the rails!

**Comment by jfranklin9000** [comment]
NICE!  NOW GIVE US TABS.

**Comment by belisarius222** [comment]
[HOON'S INCREDIBLE JOURNEY](https://ourincrediblejourney.tumblr.com/)

The "management" has cowed to the mob's demands for a return to traditional lower-case letters, so unfortunately this experiment is being shut down. I'll be maintaining a HOON CLASSIC fork for those who wish to preserve their dignity.

**Comment by ohAitch** [comment]
(I still feel like this would have been a better KEYWORD syntax than
:colons)

**Comment by mnemnion** [comment]
ahuevo

**Pull request closed without merging**
