### PR TITLE
Change ~$(a ~) to ~$(%a ~).

### PR DESCRIPTION
**Pull request by cgyarvin**

### CODE REVIEW

**Comment by ohAitch** [comment]
Alternately just stick an arbitrary twig in there, it can't _hurt_

**Comment by juped** [comment]
# *REJECTED*
Per my new policy of loudly rejecting things instead of quietly correcting them, this is loudly rejected for violating public decency standards.
I'm morbidly curious about what exactly you *do* that generates this stuff. Will accept a patch or pull-request of the changes in commit 440ebc4 on its own.

**Comment by ohAitch** [comment]
+1, I had like noticed that but didn't comment, probably wrongly so

**Comment by ohAitch** [comment]
And by "can't hurt" I mean "I ended up using ~> %live.(rap 3 %name- data ~) in one place, which should probably just be expressible as ~$  (rap 3 %name- data ~)"
That would be a ++twig type change tho

**Comment by juped** [comment]
Merged in d690fa4 with https://lwn.net/Articles/328438/ compliance

**Pull request closed without merging**
