### PR TITLE
adds error message for file-not-found to |cp, |mv, and |rm

### LINKED ISSUE #78: |rm crashes on incorrect path
So if I try to remove a node that doesn't exist with `|rm /=home=/some/broken/path` I get:

```
removed
exit
/~zod/home/~2016.3.3..03.03.07..1601/arvo/hoon:<[10.967 15].[10.998 57]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/hoon:<[10.968 15].[10.998 57]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/hoon:<[10.969 15].[10.998 57]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/hoon:<[10.971 15].[10.998 57]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/hoon:<[10.973 15].[10.998 57]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/hoon:<[10.973 29].[10.973 44]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/hoon:<[11.038 3].[11.043 13]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/hoon:<[11.040 3].[11.043 13]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/hoon:<[11.041 3].[11.043 13]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/hoon:<[11.042 5].[11.042 47]>
[%swim-take-vane %c %made ~]
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[2.789 3].[2.955 5]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[2.790 3].[2.955 5]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[2.808 3].[2.955 5]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[2.822 3].[2.955 5]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[2.827 5].[2.913 7]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[2.828 5].[2.913 7]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[2.830 7].[2.837 17]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[2.831 7].[2.837 17]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[2.832 7].[2.837 17]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[2.833 7].[2.837 17]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[2.834 7].[2.837 17]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[2.835 9].[2.836 46]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[2.836 9].[2.836 46]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[2.836 14].[2.836 46]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[709 5].[725 32]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[710 5].[725 32]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[712 5].[725 32]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[714 5].[725 32]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[714 9].[719 13]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[715 9].[719 13]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[718 11].[718 27]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[678 5].[705 51]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[679 5].[705 51]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[701 5].[705 51]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[701 9].[701 33]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[701 13].[701 33]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[1.442 7].[1.464 9]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[1.443 7].[1.464 9]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[1.445 12].[1.459 25]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[1.446 16].[1.449 55]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[1.483 7].[1.488 12]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[1.486 7].[1.488 12]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[1.486 11].[1.486 55]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[1.486 15].[1.486 55]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[1.486 27].[1.486 46]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[1.351 7].[1.401 9]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[1.352 7].[1.401 9]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[1.358 7].[1.401 9]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[1.367 7].[1.401 9]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[1.367 16].[1.401 9]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[1.368 7].[1.401 9]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[1.370 7].[1.401 9]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[1.371 7].[1.401 9]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[1.382 9].[1.383 28]>
/~zod/home/~2016.3.3..03.03.07..1601/arvo/clay:<[1.382 57].[1.382 59]>
```

One would hope for an error message, right?

### PR DESCRIPTION
**Pull request by joemfb**
I was looking through old issues for low-hanging fruit, and came across #78 ... I checked `|cp` and `|mv`, and saw that they exhibited the same behavior, so I changed them too.

I pulled the `|cp` and `|mv` implementations into `kiln`, since it's simpler to print the error that way.

Also, the assertions in `|cp` and `|mv` should probably have an associated error message, but I'm not sure what it should say. Something like *"paths &lt;a&gt; and &lt;b&gt; must have the same mark/logo/extension/final-knot"*?

closes #78

### CODE REVIEW

**Comment by juped** [comment]
Just "can't copy/move to different mark" or something. Though, the real ambitious thing would be trying to do the mark conversion, which I think involves asking ford.

**Comment by joemfb** [comment]
Thanks, I added that message. I'll look into asking ford for marks

**Comment by joemfb** [comment]
Also, should there be a zuse gate instead of the `.^(arch %cy path)` twig that I'm using everywhere?

I'm thinking of a gate that to check if a node exists, or just retrieve the `arch`, to go with `++file`, `++fray`, etc. ...

**Comment by cgyarvin** [comment]
Cool.

One thing that might be fun: adding colored text output. Ideally as a data structure for colored text, not horrible direct ansi codes.  Super useful for :talk...

**Comment by joemfb** [comment]
The data structure seems simple -- a lexicon of color names/symbols, and a new tank type: an inline text node (as, analogous to a subset of `%leaf`) with a color. Maybe `[%vein p=color q=tape]` ...

Where would the ANSI codes be applied? `++us`? `++re`?

**Comment by cgyarvin** [comment]
I hadn't thought in terms of extending ++tank; maybe.  Or just sole-effect?

Arguably, the data structure should go all the way down to C output... codes are a hack.

**Comment by joemfb** [comment]
I guess `++tank` or similar vs `sole-effect` is really about how accessible colors should to the end-programmer... (is that a thing?)

Also, I think a lexicon is too simple -- needs to handle foreground/background, and should probably handle bold, underline, blink, etc.

Another thing: at some level, you'll probably want to detect terminal capabilities, to control the mapping of colors to a subset and other such degradations

**Comment by joemfb** [comment]
BTW, I missed #125, which was the reason for `|cp` and `|mv` being implemented in the generators, not kiln. I'll roll my changes my back and implement the error-handling in the generators.

/cc @ohAitch

**Comment by cgyarvin** [comment]
++sole-effect is certainly directly generated by apps.

++tank is really a debugging text format -- it's as simple as possible
(actually, the goal is to migrate from ++tank to ++tanq) for administrative
rendering of data structures.  Making it rich is kind of beside the point.

You want to (a) anticipate this being displayed by output devices (such as
a browser) that know nothing about ANSI codes; (b) when in doubt, subset to
the minimum capabilities of a "normal" terminal.

If your feature set is too large, applications may degrade poorly.  If it's
too small, all applications work the same, but you don't get to use some
fancy bell or whistle.  So it's best, I think, to subset when in doubt.

**Comment by joemfb** [comment]
@cgyarvin, thanks for the context! I'll look into it.

I've moved the implementations back into the generators, but now I have a problem: I need print an error message and cancel when either error condition is met, but I don't have a `++toro`, so I can't use `%kiln-info`. Right now, I'm producing `~`, which results in `[%dojo-lame %made]`...

Is there a way for a generator, when used with an app, to effectively produce nothing? Or do I need to add `++poke-kiln-error` to handle exceptional conditions without emitting a move?

**Comment by joemfb** [comment]
The other option would be for me to keep the implementations in kiln, and use `++move`s to copy and move nodes, but I still haven't figured out *the right moves*<sup>TM</sub> for #191 ...

**Comment by joemfb** [comment]
@juped, this PR was in a somewhat messy state. Sorry for the confusing back-and-forth convo here ...

When the path is missing these generators log `[%dojo-lame %made]` in addition to printing the messages I added. Is that a problem? If so, I'm not sure how to solve it ...

**Comment by juped** [comment]
A pull request is a request to pull!

I don’t think that’s your problem, but if you want to fix it too, you’re welcome.

**Comment by joemfb** [comment]
I just double-checked, and it dumps the stack too ... Of course, the previous only dumped the stack, but it's hard to view this as much of an improvement

I didn't route the error messages through `++poke-kiln-info` since I don't have a `++toro`. I could  bunt `++toro` and pass that, but then it'd be included in the `abet`'ed move... is that fine?

**Pull request merged**
