### PR TITLE
READ COMMIT MESSAGE

### PR DESCRIPTION
**Pull request by theesteemedmrblowsky**
@cgyarvin @galenwp

### CODE REVIEW

**Comment by galenwp** [comment]
Yes, this is real.

**Comment by galenwp** [comment]
Will confirm out of band as well.

**Comment by galenwp** [comment]
Confirmed out of band.

**Comment by ohAitch** [comment]
*updates own ambitions accordingly*

On Fri, Dec 16, 2016 at 4:34 PM, Galen Wolfe-Pauly <notifications@github.com

**Pull request merged**
