### PR TITLE
urbit/tree@865ebc2 fix list component

### PR DESCRIPTION
**Pull request by ohAitch**

### CODE REVIEW

**Comment by juped** [comment]
I think this build contains some of the reversions. Only some of the features are back; uptwolevel, reverse comments, and comments above comment box are not back

**Comment by ohAitch** [comment]
It wasn't a revert, but rather a roll-back of the local master merge; ohAitch/fora 086f9e9 is in this PRs history, but may not be on urbit-org.

**Comment by juped** [comment]
master was merged to urbit-org for deployment, and your this branch merged on top of that. the only difference between the result and your this branch is the timeout change from urbit-org.

**Comment by ohAitch** [comment]
I think the problem is specifically with the "future of tree" post, which
got created with reverted code and consequently lacks the relevant headers.

**Comment by juped** [comment]
Good catch!

**Comment by ohAitch** [comment]
Superceded by #237

**Pull request closed without merging**
