### PR TITLE
Behn pass errors to client vanes

### PR DESCRIPTION
**Pull request by belisarius222**
This sets the groundwork for future work for vanes to handle async errors. I just added stubs to the various vanes for now, but at least they now have the error information.

A `|reset` passed, but I have not done more detailed testing on this. Not sure if there's a convenient way to test. Maybe pH?

### CODE REVIEW

**Comment by belisarius222** [comment]
I resolved a merge conflict in Clay by checking both the error in the `%wake` move and whether the wire is `%tyme`.

**Comment by belisarius222** [comment]
@philipcmonk I think I fixed Aqua; we'll see what the tests say. I added `%crud` to `+unix-task` in Zuse, and I modified `:aqua-behn` to send one as an aqua-event when it receives a Behn error. If you'd prefer different handling for that case, let me know and I can change it.

**Comment by belisarius222** [comment]
Tests passed; ready for review.

**Comment by joemfb** [comment]
@belisarius222, since this is going into `next`, do you want to coordinate the `%crud` protocol change in vere at the same time? I could do that if you'd like.

**Comment by belisarius222** [comment]
@joemfb I'm down, although I think we should get this in as-is first. I think it'll be a little cleaner that way, although I could be convinced otherwise.

**Comment by joemfb** [comment]
It looks to me like all the apps that set timers will fail if the are called with an error `%wake`. It looks like gall just prints an error in this case, but doesn't crash -- if that's right, %behn will still be unblocked in the event of app timer failure, which is the most important result.

**Pull request merged**
