### PR TITLE
Don't erase types in (lake %noun), which should always suceed

### PR DESCRIPTION
**Pull request by ohAitch**

### CODE REVIEW

**Comment by belisarius222** [comment]
This could use a comment. Maybe something like:
```
Don't verify the product type when using the %noun mark, since that would cast to *,
which would prevent the product from being used as a gate or other typed structure.
```

**Comment by belisarius222** [comment]
@ohAitch Travis build failed

**Comment by ohAitch** [comment]
I noticed, with the comment it gets a SIGTERM while trying to pill (??)

**Comment by belisarius222** [comment]
The joys of CI ... my first guess would be a timeout got triggered.

**Comment by ohAitch** [comment]
After less than a minute?

**Comment by belisarius222** [comment]
Oh ... probably not

**Comment by ohAitch** [comment]
Restarted it and it built fine, idk what exactly was going on there

**Pull request merged**
