### PR TITLE
add ++lest, the non-empty list mold builder

### PR DESCRIPTION
**Pull request by frodwith**

### CODE REVIEW

**Comment by ohAitch** [comment]
Is there a reason it's defined corecursively with `++list`, instead of just having the structure in both definitions?

**Comment by keatondunsford** [comment]
@ohAitch @frodwith If you guys think this is a good thing to have in Hoon and agree on the bad corecursive definition, want to make the structure change, then I'll merge this?

**Comment by frodwith** [comment]
Does the corecursive definiton cause a problem?

**Comment by keatondunsford** [comment]
I personally don't think it matters.

**Comment by ohAitch** [comment]
It causes you to have to look up the other definition to visually parse the mold; but the other definition is approximately right there even with the doccord gap, so probably just merge it.

**Pull request merged**
