### PR TITLE
Show message loading indicator in /stream

### PR DESCRIPTION
**Pull request by ohAitch**
+ misc stuff accumulated from master, can be rebased out if necessary

### CODE REVIEW

**Comment by juped** [comment]
Just ignore anything github says, it's always terminally confused.

**Comment by ohAitch** [comment]
No, github is right, this is a PR against urbit-org not master

Tho like the change should also get into master eventually

**Comment by juped** [comment]
As far as I'm concerned urbit-org doesn't exist, but shouldn't that ship get normal updates as well as its own junk?

**Comment by ohAitch** [comment]
The "junk" is a fast-tracked talk UI change; I think it's unsubscribed from
updates for performance-predictability reasons. But yes, merging this is a
question for @philipcmonk

**Comment by philipcmonk** [comment]
I don't think there's any problem with just merging this and putting it all
on the urbit.org ship.  The talk change is also PR'd to master somewhere?

**Comment by juped** [comment]
This is why you should never attempt to do what you're doing with git. You
end up needing to write a bot...

Yours,
r

**Comment by ohAitch** [comment]
The thing I'm attempting with git is organizational synchronization /
handoff of responsibility :P

In particular, the initial question "should I rebase all the master drift
out" is the reason I didn't just pull this in directly and push urbit-org
from prod afterwards

**Comment by juped** [comment]
I thought you were mirroring urbit.org...

Yours,
r

**Comment by ohAitch** [comment]
Mhm, this is why a pull request into the branch seemed like a good place to
discuss what should be on urbit.org

**Comment by juped** [comment]
We've ascended past this over on urbit.org

**Pull request closed without merging**
