### PR TITLE
adds AddressSanitizer to CI build

### PR DESCRIPTION
**Pull request by ohAitch**
tests urbit/urbit#915 on an actual fakezod

### CODE REVIEW

**Comment by joemfb** [comment]
Setting ASAN_OPTIONS (which is read at runtime) to ignore the shadow gap (see 0173c86df) should get you past this error.

**Comment by joemfb** [comment]
Update: that option is only successful if the binary was built with clang -- I still can't get it to work with gcc. I've updated urbit/urbit#915

**Comment by belisarius222** [comment]
This broke our CI, so let's close this until we have time to get back to work on fixing that.

**Comment by ohAitch** [comment]
s|broke our CI|broke in CI| :P

**Comment by joemfb** [comment]
As far as I can tell, the only thing that works is building vere with clang 5, and then setting some runtime options. Getting that to work will require some more back-and-forth between the urbit/urbit and urbit/arvo CI configurations. Idk how to do that without a) being a major hassle for you or @ohAitch or b) setting up my own copies of the CI infrastructure.

**Comment by ohAitch** [comment]
How far can you get on b) in 15 minutes? It should be a matter of
- auth'ing in to http://travis-ci.org
- enabling it for your fork of the urbit and arvo repos
- gem install travis to grab their cli tool
- running  travis setup releases -f  to swap the .travis.yml  deploy:
section to point at joemfb/urbit, and pushing a tag with that change
- if this successfully dumps a binary in
https://github.com/joemfb/urbit/releases, fork off this PR with
https://github.com/*joemfb*/urbit/releases/download/*tagname*
in.travis/pin-urbit-release.url,
and push that to a branch

**Pull request closed without merging**
