### PR TITLE
Zuseflat pretty

### PR DESCRIPTION
**Pull request by juped**
I want to merge this, please confirm when all is ready.

### CODE REVIEW

**Comment by cgyarvin** [comment]
This is against master, right?

**Comment by cgyarvin** [comment]
It would be very helpful to me now if this could get merged.  For some reason the reviewer is shown as Anton, but it's his change...

**Comment by juped** [comment]
Used your original merge, @ohAitch, if there's more mark fixes not in that pls send them on separately.

**Comment by ohAitch** [comment]
Oh, mostly there was an accidentally included ford printf. Is the whitespace now broken again?

**Pull request closed without merging**
